import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@component/Header";

import { PrimeReactProvider } from "primereact/api";
import Tailwind from "primereact/passthrough/tailwind";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <PrimeReactProvider value={{ unstyled: true, pt: Tailwind }}>
        <body className={inter.className}>
          <Header />
          <main className="flex min-h-screen flex-col items-center justify-between p-24">
            {children}
          </main>
        </body>
      </PrimeReactProvider>
    </html>
  );
}
